
-- ================================================================
--   Which medical conditions drive the highest billing amounts?
--   How does admission type affect billing within each condition?
-- ================================================================
--   Understanding cost drivers by condition helps hospitals plan budgets, negotiate insurance rates, and identify high-cost areas.
-- ================================================================
SELECT
    c.condition_name AS condition,
    f.admission_type AS admission_type,

    COUNT(*) AS total_admissions,

    -- Average billing amount for this condition and admission type.
    CAST(
        AVG(f.billing_amount)
        AS DECIMAL(12,2)
    ) AS avg_billing_cad,

    -- Lowest billing amount observed.
    CAST(
        MIN(f.billing_amount)
        AS DECIMAL(12,2)
    ) AS min_billing_cad,

    -- Highest billing amount observed.
    CAST(
        MAX(f.billing_amount)
        AS DECIMAL(12,2)
    ) AS max_billing_cad,

    -- Total billing amount generated by this condition and admission type.
    CAST(
        SUM(f.billing_amount)
        AS DECIMAL(15,2)
    ) AS total_billing_cad,

    -- Average length of stay in days.
    CAST(
        AVG(CAST(f.length_of_stay_days AS FLOAT))
        AS DECIMAL(6,1)
    ) AS avg_los_days,

    -- Rank each condition by average billing within each admission type.
    
    RANK() OVER (
        PARTITION BY f.admission_type
        ORDER BY AVG(f.billing_amount) DESC
    ) AS billing_rank_within_type

FROM dbo.fact_admissions AS f

JOIN dbo.dim_condition AS c
    ON f.condition_id = c.condition_id

GROUP BY
    c.condition_name,
    f.admission_type

ORDER BY
    f.admission_type,
    billing_rank_within_type;
GO
